name: "Follistatin"
description: "Muscle growth and fat reduction therapeutic protein"

default_effects:
  physical:
    muscle_mass_change: 2.0  # lbs
    fat_mass_change: -2.0    # lbs
    
  longevity:
    lifespan_increase: 2.5   # percentage
    
  biomarkers:
    egfr_change: 5.0         # mL/min/1.73m²
    cystatin_c_change: -0.2  # mg/L

  healthcare:
    hospital_visit_reduction: 15.0  # percentage
    
impact_modifiers:
  muscle_to_falls: 0.1       # Each lb of muscle reduces falls by 10%
  lifespan_to_gdp: 0.8      # 80% of lifespan increase converts to GDP
  health_quality: 0.05       # 5% improvement in quality of life
  kidney_to_medicare: 0.10   # Kidney biomarker improvements reduce costs by 10% 