name: "Intervention Name"
description: "Brief description of the intervention mechanism"

default_effects:
  physical:
    muscle_mass_change: 0.0  # Average change in lean muscle mass (lbs)
    fat_mass_change: 0.0    # Average change in fat mass (lbs)
    
  longevity:
    lifespan_increase: 0.0  # Mean percentage increase in lifespan
    
  biomarkers:
    egfr_change: 0.0        # Change in eGFR (mL/min/1.73m²)
    cystatin_c_change: 0.0  # Change in Cystatin C (mg/L)

  healthcare:
    hospital_visit_reduction: 0.0  # Percentage reduction in hospital visits
    
impact_modifiers:
  muscle_to_falls: 0.0      # Fraction of falls reduced per lb muscle gained
  lifespan_to_gdp: 0.0      # Fraction of lifespan increase contributing to GDP
  health_quality: 0.0       # QALY score improvement
  kidney_to_medicare: 0.0   # Medicare cost reduction per unit kidney function

# Notes:
# 1. All values should be based on clinical evidence where possible
# 2. Use conservative estimates when evidence is limited
# 3. Document sources for parameter values in comments
# 4. Values must be within ranges specified in schema.json
# 5. All parameters are required - do not delete any fields 